apiVersion: skaffold/v4beta11
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: long-stack-426216-q2
  artifacts:
    - image: us-central1-docker.pkg.dev/long-stack-426216-q2/tickets-repo/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
